import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black fixed inset-0 flex items-center justify-center`}
      >
        <div className="p-4 bg-white w-[93vw] h-[95vh] rounded-lg">
          {/* Scrollable inner content */}
          <div
            className="h-full overflow-auto p-6 scrollbar-thin scrollbar-thumb-gray-400 scrollbar-track-gray-200"
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
