import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black flex items-center justify-center h-svh p-4`}
      >
        <div className="m-[1%] bg-white h-[95vh] rounded-xl flex-1 overflow-hidden">
          {/* Scrollable inner content */}
          <div className="flex-1 h-full overflow-hidden overflow-y-auto p-6 scrollbar-thin scrollbar-thumb-gray-400 scrollbar-track-white">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
